name: 02-workflow events

on: 
   push:
   pull_request:
   schedule:
      - cron: '*/5 * * * *'
   workflow_dispatch:

jobs: 
    echo:
        runs-on: ubuntu-latest
        steps:
        - name: show the trigger event for this
          run: echo "i am trigered by ${{github.event_name}}"


