name: 08-variables

on:
 push:
 workflow_dispatch: 

env:
  OVERRIDE_VAR: "i am at gitflow level"
  WORKFLOW_VAR: " in am workflow var"

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
          OVERRIDE_VAR: "i am at Job Level"
        steps: 
            - name: print variables
              env:
                STEP_VAR: "i am step variable"
                OVERRIDE_VAR: "i am at step level"
              run: |
                echo "step var: ${{env.STEP_VAR}}"
                echo "overddie var: ${{env.OVERRIDE_VAR}}"
                echo "workflow var: ${{env.WORKFLOW_VAR}}"

              
