name: 18.1 reusable workflow

on:
  workflow_call:
    inputs:
        target_directory:
            type: string
            required: true
    outputs:
        build_status:
            description: the status of the build process
            value: ${{jobs.deploy.outputs.build_status}}
        url:
            description: the url of the deployed version
            value: ${{jobs.deploy.outputs.url}}

jobs:
   deploy:
      runs-on: ubuntu_latest
      outputs:
        build_status: ${{steps.build.outputs.status}}
        url: ${{steps.deploy.outputs.url}}
      steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: Build
          id: build
          run: |
            echo " building using the directory ${{inputs.target_directory}}"
            echo "build-status-success" >> "$GITHUB_OUTPUT"
        - name: Deploy
          id: deploy
          run: | 
            echo "Deploying build Artifact"
            echo "url=https://www.google.com" "$GITHUB_OUTPUT"